import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/Footer';
import Newsletter from './components/Newsletter';
import Header from './components/Header';
import MyTabs from './components/Home';
import CenterLayout from './components/CenterLayout';
import MyInfo from './components/MyInfo';
import Tittle from './components/Tittle';
import PostMenu from './components/PostMenu';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
       <PostMenu />
        <CenterLayout>
          <MyInfo />
         <MyTabs />
           
        {children}
       </CenterLayout>

        <Newsletter />
        <Footer />
        </body>
      <Analytics />
    </html>
  )
}
